
server:
  port: 9005 #指定启动端口号
  servlet:
    context-path: /mdzz

spring:
  profiles:
    active: dev #默认环境(开发环境)
  thymeleaf:
    cache: false
  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource   #这里是配置druid连接池，以下都是druid的配置信息
    url: jdbc:mysql://127.0.0.1:3306/example?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password:
  application:
    name: logindemo

mybatis:
  mapper-locations: classpath*:/mapper/**Mapper.xml    #把xml文件放在com.XX.mapper.*中可能会出现找不到的问题，这里把他放在resource下的mapper中
  typeAliasesPackage: com.test.domain        #这里是实体类的位置，#实体扫描，多个package用逗号或者分号分隔
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false

